###########
# site.title, site.url, site.author.name

title:   'Jekyll Minimal Theme'

## was:
#   url:     'http://drjekyllthemes.github.io/jekyll-minimal-theme'
#  use absolute path (without https/http for now to make it work with both
url: /jekyll-minimal-theme  
author:
  name:  'Jekyll Minimal Theme Team'


########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

permalink: /:title.html

exclude:
- README.md


safe: true
lsi: false

