###########
# site.title, site.url, site.author.name

title:   'Jekyll Minimal Theme'
url:     'http://feedreader.github.io/jekyll-minimal-theme'
author:
  name:  'Jekyll Minimal Theme Team'


########
# more settings

markdown: kramdown


exclude:
- README.md


safe: true
lsi: false

